### ISSUE TITLE
SDK seems not maintained. Dependencies are outdated and unit tests are failing locally.

### ISSUE THREAD

**Issue by sachushaji** [bnb-chain/javascript-sdk#381]
Seems the dependencies are out dated. Npm audit gives a lot of critical issues with the current dependencies. Kindly update them.

<img width="728" alt="image" src="https://github.com/bnb-chain/javascript-sdk/assets/15767732/50fdb7e4-c9bd-4504-b41c-6b366559973d">

Running the unit tests locally, Many are failing (used node v14.18)
<img width="743" alt="image" src="https://github.com/bnb-chain/javascript-sdk/assets/15767732/0ef1b36a-1456-4321-950c-55d9f0784509">

**Comment by robot-ux** [comment]
fixed by https://github.com/bnb-chain/javascript-sdk/pull/382

**Comment by sachushaji** [comment]
Hi @robot-ux , Thanks for updating the dependencies, but I can see that the unit tests are still failing.
<img width="1310" alt="image" src="https://github.com/bnb-chain/javascript-sdk/assets/15767732/fd1456f4-156d-4dbe-9ddc-ba9d333835d4">
used node version 14.18.1

**Comment by declangg** [comment]
> Hi @robot-ux , Thanks for updating the dependencies, but I can see that the unit tests are still failing. <img alt="image" width="1310" src="https://user-images.githubusercontent.com/15767732/238137339-fd1456f4-156d-4dbe-9ddc-ba9d333835d4.png"> used node version 14.18.1

Looks like unit test hasn't been updated in over 3 years, let me try to get it working, but I believe the SDK is working as many of our projects are using it

**Comment by robot-ux** [comment]
> Hi @robot-ux , Thanks for updating the dependencies, but I can see that the unit tests are still failing. <img alt="image" width="1310" src="https://user-images.githubusercontent.com/15767732/238137339-fd1456f4-156d-4dbe-9ddc-ba9d333835d4.png"> used node version 14.18.1

Looks like unittest hasn't been updated in over 3 years, let me try to get it working, but I believe the SDK is working as many of our projects are using it
